"""empty message

Revision ID: 084d780f214c
Revises: 9ec39ea7959c
Create Date: 2022-01-03 22:14:38.713480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "084d780f214c"
down_revision = "9ec39ea7959c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "riddles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("discount", sa.Float(), nullable=True),
        sa.Column(
            "status", sa.Enum("available", "archived", name="state"), nullable=False
        ),
        sa.Column("questions", sa.Text(), nullable=False),
        sa.Column("answers", sa.Text(), nullable=False),
        sa.Column("number_of_questions", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("riddles")
    # ### end Alembic commands ###
