"""empty message

Revision ID: 2036845b6c2b
Revises: 3d8d9ddec99f
Create Date: 2022-08-16 21:14:56.510283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2036845b6c2b"
down_revision = "3d8d9ddec99f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("hint", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "hint")
    # ### end Alembic commands ###
