b"""empty message

Revision ID: e372adf82e7c
Revises: a9612a3343d5
Create Date: 2022-08-16 19:16:19.312112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e372adf82e7c"
down_revision = "a9612a3343d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "riddles", sa.Column("duration", sa.String(length=255), nullable=True)
    )
    op.add_column("riddles", sa.Column("where", sa.String(length=255), nullable=True))
    op.add_column("riddles", sa.Column("google_map", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("riddles", "google_map")
    op.drop_column("riddles", "where")
    op.drop_column("riddles", "duration")
    # ### end Alembic commands ###
